server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db_new?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 170805
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    username: yourmail@gmail.com
    password: '***********'
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: messages
    encoding: UTF-8

file:
  upload-dir: ./uploads

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
